# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
FASTLANE_USER="nttoan26@yahoo.com"
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="vktk-hoon-orqk-bspq"


default_platform(:ios)

platform :ios do
  
  lane :screenshots do
    capture_screenshots(
      scheme: "AppUITests",
      languages: [ "en-US", "fr-FR" ],
      output_directory: "./fastlane/screenshots",
      devices: [
        "iPhone 15 Plus",
      ],
      output_simulator_logs: false,
      headless: true,
      dark_mode: false,
      buildlog_path: "./build_log",
      clear_previous_screenshots: true
    )
    upload_to_app_store(
      skip_binary_upload: true,
      run_precheck_before_submit: false,
      submit_for_review: false,
      skip_app_version_update: true,
      automatic_release: false,
      skip_metadata: true,
      skip_screenshots: false,
    )
  end

  lane :test do
    run_tests(scheme: "App")
  end

  lane :submit_testflight_build do
    sync_code_signing(type: "adhoc")
    increment_version_number_in_xcodeproj(scheme: "App", version_number: "1.2")
    # increment_build_number_in_xcodeproj(scheme: "App")
    increment_build_number
    build_app(scheme: "App")
    upload_to_testflight(
      changelog: "remove support for iPad",
      beta_app_description: "beta version desc",
      beta_app_review_info: {
        contact_email: "email@email.com",
        contact_first_name: "Connect",
        contact_last_name: "API",
        contact_phone: "4696041497",
        demo_account_name: "demo@email.com",
        demo_account_password: "connectapi",
        notes: "this is review note for the reviewer <3 thank you for reviewing"
      },
      localized_app_info: {
        "default": {
          feedback_email: "default@email.com",
          marketing_url: "https://example.com/marketing-default",
          privacy_policy_url: "https://example.com/privacy-default",
          description: "Default description",
        },
        "en-GB": {
          feedback_email: "en-gb@email.com",
          marketing_url: "https://example.com/marketing-en-gb",
          privacy_policy_url: "https://example.com/privacy-en-gb",
          description: "en-gb description",
        }
      },
      localized_build_info: {
        "default": {
          whats_new: "hihihi",
        },
        "en-GB": {
          whats_new: "hahaha",
        }
      }
    )
  end

  lane :submit_build do
    upload_to_app_store(
      # build_number: '55',
      skip_binary_upload: true,
      run_precheck_before_submit: false,
      submit_for_review: true,
      skip_app_version_update: true,
      automatic_release: false,
      skip_metadata: true,
      skip_screenshots: true,
    )
  end

  lane :update_metadata do
    precheck(default_rule_level: "warn")
    upload_to_app_store(
      run_precheck_before_submit: false,
      edit_live: false,
      skip_binary_upload: true,
      skip_screenshots: true,
      skip_app_version_update: true,
      force: true,
      submission_information: {
        add_id_info_uses_idfa: false,
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        content_rights_contains_third_party_content: true
      }
    )
  end

  lane :add_tester do
    upload_to_testflight(
      skip_submission: true,
      distribute_only: true,
      first_name: "Toan",
      last_name: "Nguyen",
      email: "nttoan26@yahoo.com"
    )
  end

  lane :register_devices_adhoc do
    register_devices(
      devices: {
        "Luka iPhone 6" => "1234567890123456789012345678901234567890",
    })
    sync_code_signing(force_for_new_devices: true, type: "adhoc")
  end
end
